### ISSUE TITLE
Class 'App\Providers\StatusPage' not found

### ISSUE THREAD

**Issue by LaravelLover069** [davidpiesse/nova-statuspage#4]
Hi David, I just installed your Nova StatusPage Card but when I refresh Nova I get following error:

Class 'App\Providers\StatusPage' not found 

![Bildschirmfoto vom 2021-06-16 12-13-28](https://user-images.githubusercontent.com/81033249/122201409-4acb7580-ce9c-11eb-94e8-778d4ad8b4ef.png)

![Bildschirmfoto vom 2021-06-16 12-10-33](https://user-images.githubusercontent.com/81033249/122201432-50c15680-ce9c-11eb-84d4-c62e6e4647a9.png)

Is there any mandatory class which I need to include in the NovaServiceProvider header?

**Comment by davidpiesse** [comment]
You probably need to scope with a ```use``` statement 
Something like ``` use Davidpiesse\StatusPage\StatusPage ```

**Comment by LaravelLover069** [comment]
Awesome, works perfectly :) Maybe worth noting that this line shall be added in the docs.

Thanks David!
